### ISSUE TITLE
This is a wrong issue, you don't need to see it, it will waste your time

### ISSUE THREAD

**Issue by thinkerofwp** [DuGuQiuBai/Java#24]

**Comment by Mark-Yang-tech** [comment]
Don't sent the spam for me again


 
---Original---

**Comment by wpaiwm** [comment]
But you are ridiculous, so I have to harass you

 
  

 

 ------------------ 原始邮件 ------------------
  发件人: "Mark-Yang-tech"<notifications@github.com>;
 发送时间: 2019年9月16日(星期一) 中午12:45
 收件人: "DuGuQiuBai/Java"<Java@noreply.github.com>;
 抄送: "~ "<1228605963@qq.com>;"State change"<state_change@noreply.github.com>;
 主题: Re: [DuGuQiuBai/Java] so what is it (#24)

 

Don't sent the spam for me again 



---Original---

**Comment by Mark-Yang-tech** [comment]
Why am I ridiculous I just copied your Repository


 
---Original---

**Comment by anotnow** [comment]
？


 
---Original---

**Comment by wpaiwm** [comment]
I'm not talking about you, and this isn't mine, either. I'm talking about the man who became a Java god in 27 days.
  I didn't send you any junk mail either. I think I should submit an issue and then there will be mail or something like that.So you don't have to email me specifically to tell me that you don't have to spam you.Do you understand me


  

 ------------------ 原始邮件 ------------------
  发件人: "Mark-Yang-tech"<notifications@github.com>;
 发送时间: 2019年9月16日(星期一) 中午1:00
 收件人: "DuGuQiuBai/Java"<Java@noreply.github.com>;
 抄送: "~ "<1228605963@qq.com>;"State change"<state_change@noreply.github.com>;
 主题: Re: [DuGuQiuBai/Java] so what is it (#24)

 

Why am I ridiculous I just copied your Repository 



---Original---

**Comment by shellyaoo** [comment]
？



xiachener@foxmail.com
 
From: 情未晞
Date: 2019-09-16 13:30
To: DuGuQiuBai/Java
CC: Subscribed
Subject: Re: [DuGuQiuBai/Java] so what is it (#24)
？ 



---Original---
